[project]
name = "try3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hayayha1", email = "18045280915@163.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
try3 = "try3:main"

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
